language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
install: "pip install -r requirements.txt --use-mirrors"
script:
  - python setup.py nosetests
after_success:
  coveralls
